<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use App\Models\User;

class OperatorController extends Controller
{
    /**
     * List all Sales Operators
     */
    public function index()
    {
        $operators = User::where('role', 'operator')
            ->orderBy('created_at', 'desc')
            ->get()
            ->map(function ($user) {
                // Count invoices generated by this operator name
                $invoiceCount = DB::table('invoices')
                    ->where('operator_name', $user->name)
                    ->count();

                $totalSales = DB::table('invoices')
                    ->where('operator_name', $user->name)
                    ->sum('grand_total');

                return [
                    'id' => $user->id,
                    'name' => $user->name,
                    'email' => $user->email,
                    'phone' => $user->phone,
                    'assignedDepot' => $user->organization,
                    'status' => $user->status,
                    'totalInvoices' => $invoiceCount,
                    'totalSales' => (float) $totalSales,
                    'joinedDate' => $user->created_at ? $user->created_at->format('Y-m-d') : date('Y-m-d'),
                ];
            });

        return response()->json([
            'success' => true,
            'data' => $operators
        ]);
    }

    /**
     * Create a New Sales Operator Account
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|min:3|max:100',
            'email' => 'required|email|max:150|unique:users,email',
            'phone' => 'required|string|min:10|max:20',
            'assignedDepot' => 'nullable|string|max:200',
            'assigned_depot' => 'nullable|string|max:200',
            'password' => 'required|string|min:4',
            'status' => 'nullable|string|in:ACTIVE,SUSPENDED'
        ]);

        $assignedDepot = $request->input('assignedDepot') ?? $request->input('assigned_depot');

        $user = User::create([
            'name' => $validated['name'],
            'email' => strtolower(trim($validated['email'])),
            'password' => Hash::make($validated['password']),
            'role' => 'operator',
            'phone' => $validated['phone'],
            'organization' => $assignedDepot,
            'status' => $validated['status'] ?? 'ACTIVE'
        ]);

        return response()->json([
            'success' => true,
            'message' => "Sales Operator account created successfully for {$user->name}.",
            'data' => [
                'id' => $user->id,
                'name' => $user->name,
                'email' => $user->email,
                'phone' => $user->phone,
                'assignedDepot' => $user->organization,
                'status' => $user->status
            ]
        ], 201);
    }

    /**
     * Update Operator Status (ACTIVE / SUSPENDED)
     */
    public function updateStatus(Request $request, $id)
    {
        $validated = $request->validate([
            'status' => 'required|string|in:ACTIVE,SUSPENDED'
        ]);

        $user = User::where('id', $id)->where('role', 'operator')->first();

        if (!$user) {
            return response()->json(['success' => false, 'message' => 'Operator not found.'], 404);
        }

        $user->status = $validated['status'];
        $user->save();

        return response()->json([
            'success' => true,
            'message' => "Operator {$user->name} status changed to {$validated['status']}."
        ]);
    }

    /**
     * Reassign Operator to a Different Depot / Location
     */
    public function updateLocation(Request $request, $id)
    {
        $depot = $request->input('assignedDepot') ?? $request->input('assigned_depot');
        if (!$depot) {
            return response()->json(['success' => false, 'message' => 'Assigned depot is required.'], 422);
        }

        $user = User::where('id', $id)->where('role', 'operator')->first();

        if (!$user) {
            return response()->json(['success' => false, 'message' => 'Operator not found.'], 404);
        }

        $user->organization = $depot;
        $user->save();

        return response()->json([
            'success' => true,
            'message' => "Operator {$user->name} reassigned to {$depot}."
        ]);
    }

    /**
     * Reset Operator Terminal PIN / Password
     */
    public function resetPin(Request $request, $id)
    {
        $validated = $request->validate([
            'newPin' => 'required|string|min:4'
        ]);

        $user = User::where('id', $id)->where('role', 'operator')->first();

        if (!$user) {
            return response()->json(['success' => false, 'message' => 'Operator not found.'], 404);
        }

        $user->password = Hash::make($validated['newPin']);
        $user->save();

        return response()->json([
            'success' => true,
            'message' => "Terminal access PIN for {$user->name} has been reset successfully."
        ]);
    }
}
